name: Real Estate Alerts

on:
  schedule:
    - cron: '50 21 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests xmltodict pandas

      - name: Run alert script
        run: python tenhill_final.py

      - name: Commit seen.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add seen.json
          git commit -m "update seen.json" || echo "no changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
