name: Tenhill Auto Alert with Memory

on:
  schedule:
    - cron: '50 21 * * *'  # 오전 6시 50분 KST
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install requests xmltodict pandas

      - name: Run alert script
        run: |
          python tenhill_final.py

      - name: Commit seen.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add seen.json
          git commit -m "update seen.json" || echo "No changes to commit"
          git push
